FROM python:3.11-slim

WORKDIR /app

# Copiar shared
COPY shared/ /home/ubuntu/dfs-system/shared/

# Copiar metadata-service
COPY metadata-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY metadata-service/ .

EXPOSE 8000

CMD ["python", "main.py"]
